#! /bin/bash
set -e # halt script on error

gcc -c main.c
gcc -c timespectools.c
gcc -c module_interface.c
gcc -c tasks.c

gcc -o main main.o timespectools.o tasks.o module_interface.o -pthread

rm main.o timespectools.o tasks.o module_interface.o